### ISSUE TITLE
Problem with color_track_behavior.py 

### ISSUE THREAD

**Issue by Onydus** [PacktPublishing/Learn-Robotics-Fundamentals-of-Robotics-Programming#4]
Hello again, Danny

I hope you are well.

My apologies for bothering you again. I'm sure you have better things to do. However, I've come across a bit of a road block while working through this section of your book. 

This is the error message being outputted into the console: 

![color_tracking](https://user-images.githubusercontent.com/57407114/87877389-55586300-c9de-11ea-9a82-09530288efe9.png)

Again, resorting to copying the code directly from github, the only edit I have made to the original is this:
**"contours = cv2.findContours(contour_image, cv2.RETR_LIST, cv2.CHAIN_APPROX_SIMPLE)[0]"**
Suggested by you to a fellow reader on the raspberrypi forum. 

I'm completely stumped. 

Kind regards,
Onydus

**Comment by dannystaple** [comment]
Hello, first - it doesn't bother me to have book queries and inquiries. It's all good material to create an FAQ or improve things in follow-up books.

The callback set to none warning is unrelated to this- this is the cleanup code.

So I'm assuming this is the visual processing area. The OpenCV API has changed between the version I'd installed in the original book and now.

This code seems to work with a current version of OpenCV:
```
  contours = cv2.findContours(masked, cv2.RETR_LIST, cv2.CHAIN_APPROX_SIMPLE)[0]
  circles = [cv2.minEnclosingCircle(cnt) for cnt in contours]
```

Some questions so I can try to reproduce this:
* Which version of Python are you running?
* How did you install OpenCV for python?
* What OpenCV packages do you get when you type `pip freeze` or `pip3 freeze`?
* What do you get if you add `print(repr(contours)` before the circles line?

**Comment by Onydus** [comment]
Danny,

My apologies for the delayed response. I've been called away abroad on business and didn't want to risk bringing my robot with me (could look suspicious to the uninitiated eye in airport security). As soon as I'm home I'll be getting back into it and implementing your updated code and answering your questions. Again, my apologies, I wasn't expecting to be stuck over here for so long! Thank you for your time.

Hope you and your family are well.

Kind regards,
Onydus

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Onydus** [comment]
Danny,

I'm truly sorry that I was unable to reply to your questions regarding my robot issues. It's been a crazy time, unfortunately, as you're aware, I'm sure.
I want to let you know that I really appreciate the time you spent helping me.
Thank you.

All the best,
Onydus

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by dannystaple** [comment]
Hello Onydus,

Did you manage to get the updated code to work on the robot? Have you done any robotics projects since?
I hope things have settled a bit more now! It was a strange year or so for us all!

Danny

**Comment by Onydus** [comment]
Hey Danny,

It's good to hear from you again.
I'm sorry but I got distracted with another robot, and didn't get around to updating the code yet!
Thanks to what I learned from you I was able to build this one! (see attached). As before, I got even more creative with the 3D printers! Haha
This one sanitises floors for my local taekwondo gym. I've named it Temple Keeper so far. I've also built a robot wars spec 'robot' to cut my lawn. It currently wants to do 12mph all the time but I just can't bring myself to dial down in the motor speeds :')
I'd like to thank you again for your help, and the inspiration your book gave me on my journey in robotics. I was even able to use my projects to convince a university to let me onto their robotics degree course. I start tomorrow 😄

It was indeed a strange and crazy period.

I hope you are doing well. What have you been working on? Any more books in the pipeline? I'm always on the lookout for some good books on the subject.

Kind regards,
Onydus (Rowan Hansard)



________________________________

**Comment by dannystaple** [comment]
Hi Onydus,
That sounds interesting indeed - any links or photos of it? I didn't get the attachment there. 3D printers are such an awesome addition to making robots - I use mine a lot, although not for book robots, as the concern there is how much of the audience have access to them. I want to make a book focusing on 3D printable robot projects one day though. Hexapods, arms, heads, hands and so on.

Robotics degree course! Amazing!

I am working on a 3rd book - this time a Raspberry Pi Pico robotics book and trying for a faster-paced style. Just hope it won't make it harder to follow, although it's aimed at a reader who has done a little more than the first book. I'll be putting in a chapter skimming FreeCAD design, which is turning out to be quite tricky (and may need more than one chapter) - just to kickstart CAD thinking in a reader. Also, there will be scratch building chassis and using Monte-Carlo simulation to estimate a robot's position in a known space.

Anyway, thanks for getting back to me - always excited to see what people have been building.

Danny
