### ISSUE TITLE
test_encoders.py

### ISSUE THREAD

**Issue by art725** [PacktPublishing/Learn-Robotics-Fundamentals-of-Robotics-Programming#5]
Hi Danny,

Looks like there's an error in the encoders file. It also appears that you've answered this question on a forum, but i saw it's still missing in your repo.
https://www.raspberrypi.org/forums/viewtopic.php?t=265498
![image](https://user-images.githubusercontent.com/54814722/99824101-d5bcdb00-2b1a-11eb-9695-6b3a92eb0feb.png)

**Comment by dannystaple** [comment]
Hello, this code was based on an older version of the GPIOZero library. The second edition repo should take care of this.
